<!Doctype html>
<html>

<head>
    <title> Task-17.2 </title>

    <head>

    <body>
        <h3> Exception Handling </h3>

        <script>

            function divide(dividend, divisor) {
                if (divisor === 0) {
                    throw new Error("Divide by zero error");
                }
                return dividend / divisor;
            }

            try {

                const result = divide(10, 0);
                console.log(result);
            }

            catch (error) {
                console.error("Error:", error.message);
            }


        </script>


    </body>

</html>